---
- name: Node-Expoter Install | Download nodex-exporter {{ node_exporter_version }}
  get_url:
    url: "{{ node_exporter_download_url }}"
    dest: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
  register: download

- name: Node-Expoter Install | Create directory
  file:
    path: "{{ node_exporter_home }}"
    state: directory

- name: Node-Expoter Install | Untar archive
  unarchive:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: "{{ node_exporter_home }}"
    extra_opts: [--strip-components=1]
    remote_src: true

- name: Nodex-Exporter Install | Create systemd unit
  template:
    src: node-exporter.service
    dest: "{{ systemctl_path }}"

- name: Nodex-Exporter Install | Reload and Start systemd unit node-expoter
  systemd:
    state: restarted
    daemon_reload: true
    name: node-exporter

