---
- hosts: all
  gather_facts: true
  become: true
  become_method: sudo

  tasks:
    - name: Stop services
      systemd:
        daemon_reload: no
        name: "{{ item }}"
        state: stopped
        enabled: yes
      with_items:
        - node-exporter
        - victoriametrics-vmagent
        - victoriametrics-vminsert
        - victoriametrics-vmstorage
        - victoriametrics-vmselect
      ignore_errors: true

    - block:
      - name: Collect files and directories
        find:
          paths: "{{ item.0 }}"
          patterns: "{{ item.1 }}"
          hidden: True
          recurse: True
          file_type: any
        with_nested:
          - ['/etc/','/run/','/tmp','/usr/local/bin']
          - ['node-expoter', 'victoriametrics*', 'vmagent', 'vminsert', 'vmselect', 'vmstorage'] 
        register: collected_files_directories

      # - name: debug
      #   debug:
      #     msg: "{{ item.1.path }}"
      #   with_items:
      #     - "{{ collected_files.results | subelements('files') }}"

      - name: Remove directories and files
        file:
          path: "{{ item.1.path }}"
          state: absent
        with_items:
          - "{{  collected_files_directories.results | subelements('files') }}"



